name: fine695
channels:
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  # Core computation and ML - Conda managed
  - python=3.11
  - pip
  - numpy>=1.26
  - scipy
  - pandas>=2.2
  - scikit-learn>=1.4
  - cython>=3.0 # often a build dep for pip packages

  # Key ML Libraries also available on Conda, specify versions for some stability
  - catboost>=1.2
  - lightgbm>=4.0
  - xgboost>=2.0
  
  # Arrow for Parquet, keep version range for now
  - arrow-cpp>=12.0.1,<13.0.0
  - libarrow>=12.0.1,<13.0.0
  - pyarrow # This will be installed by pip, but listing here for clarity if needed

  # Common utilities
  - bzip2
  - ca-certificates
  - certifi
  - openssl
  - readline
  - sqlite
  - tk # Sometimes needed by matplotlib, even if not directly used for GUI
  - xz
  - zlib
  - ncurses # for terminal interactions

  # Other potentially useful, but less critical, can be removed if still problematic
  - joblib
  - tqdm
  - pyyaml>=6.0
  - jinja2 # often a dep for templating in other libs
  - requests
  - setuptools
  - wheel

  # PIP section for packages best managed by pip or not on conda-forge easily
  # or where we want specific versions from pip
  - pip:
      - accelerate==1.7.0
      - adagio==0.2.6
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.4
      - aiohttp-cors==0.8.1
      - aiosignal==1.3.2
      - alembic==1.16.1
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - attrs==25.3.0
      - autogluon==1.3.1
      - autogluon-common==1.3.1
      - autogluon-core==1.3.1
      - autogluon-features==1.3.1
      - autogluon-multimodal==1.3.1
      - autogluon-tabular==1.3.1
      - autogluon-timeseries==1.3.1
      - beartype==0.21.0
      - beautifulsoup4==4.13.4
      - blis==1.2.1
      - boto3==1.38.25
      - botocore==1.38.25
      - cachetools==5.5.2
      - catalogue==2.0.10
      - cffi==1.17.1
      - click==8.2.1
      - cloudpathlib==0.21.1
      - cloudpickle==3.1.1
      - colorful==0.5.6
      - colorlog==6.9.0
      - confection==0.1.5
      - coreforecast==0.0.15
      - cryptography==42.0.8
      - cymem==2.0.11
      - datasets==2.14.4
      - defusedxml==0.7.1
      - dill==0.3.7
      - distlib==0.3.9
      - docker==7.1.0
      - evaluate==0.4.3
      - fastai==2.8.2
      - fastcore==1.8.2
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - fasttransform==0.0.2
      - frozenlist==1.6.0
      - fs==2.4.16
      - fugue==0.9.1
      - future==1.0.0
      - gdown==5.2.0
      - gluonts==0.16.1
      - google-api-core==2.24.2
      - google-auth==2.40.2
      - googleapis-common-protos==1.70.0
      - hf-xet==1.1.2
      - huggingface-hub==0.32.2
      - hydra-core==1.3.2
      - hyperopt==0.2.7
      - imageio==2.37.0 # Used by autogluon.multimodal
      - jmespath==1.0.1
      - json5==0.12.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - lean==1.0.218
      - lightning==2.5.1.post0
      - lit-saint==0.4.1
      - llvmlite==0.44.0 # Numba dependency
      - lxml==5.4.0
      - mako==1.3.10
      - marisa-trie==1.2.1
      - matplotlib # Matplotlib itself via pip
      - mlforecast==0.13.6
      - model-index==0.1.11
      - msgpack==1.1.0
      - multidict==6.4.4
      - multiprocess==0.70.15
      - murmurhash==1.0.13
      - nlpaug==1.1.11
      - nltk==3.8.1
      - numba==0.61.2 # For performance in some libraries
      - nvidia-ml-py3==7.352.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.11
      - optuna==4.3.0
      - ordered-set==4.1.0
      - orjson==3.10.18
      - packaging==24.2
      - patsy==1.0.1 # Statsmodels dependency
      - pdf2image==1.17.0 # Used by autogluon.multimodal
      - pillow>=9.5.0 # More recent Pillow via pip, autogluon needs >9.2
      - platformdirs==4.3.8
      - plotly # Plotly via pip
      - plum-dispatch==2.5.7
      - preshed==3.0.10
      - prometheus-client==0.22.0
      - propcache==0.3.1
      - proto-plus==1.26.1
      - psutil==7.0.0
      - py-spy==0.4.0
      - py4j==0.10.9.9
      - pyarrow==20.0.0 # Pinning pyarrow in pip as it's key
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pytesseract==0.3.13 # Used by autogluon.multimodal
      - pytorch-lightning==1.9.5 # Pinned for lit-saint, consider unpinning or matching autogluon's PTL if different
      - pytorch-metric-learning==2.8.1
      - pytorch-tabnet # Let pip handle this
      - pytorch-tabular # Let pip handle this
      - quantconnect-stubs==17122
      - ray==2.44.1
      - referencing==0.36.2
      - regex==2024.11.6
      - rich # Rich via pip
      - rpds-py==0.25.1
      - rsa==4.9.1
      - s3transfer==0.13.0
      - safetensors==0.5.3
      - scikit-image==0.25.2 # Used by autogluon.multimodal
      - sentencepiece==0.2.0
      - seqeval==1.2.2
      - shellingham==1.5.4
      - smart-open==7.1.0
      - soupsieve==2.7
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.41
      - srsly==2.5.1
      - statsforecast==2.0.1
      - statsmodels==0.14.4 # Statsmodels via pip
      - sympy==1.13.1 # Pinned to avoid torch conflict
      - tabulate==0.9.0
      - tensorboard # Tensorboard via pip
      - tensorboardx==2.6.2.2
      - text-unidecode==1.3
      - thinc==8.3.4
      - tifffile==2025.5.26 # Used by autogluon.multimodal
      - timm==1.0.3 # Used by autogluon.multimodal
      - tokenizers==0.21.1
      - toolz==0.12.1
      - torch==2.6.0 # Pinning torch for consistency
      - torchvision==0.21.0 # Pinning torchvision to match torch
      - transformers==4.49.0
      - triad==0.9.8
      - typer==0.16.0
      - typing-inspection==0.4.1
      - utilsforecast==0.2.10
      - virtualenv==20.31.2
      - wasabi==1.1.3
      - weasel==0.4.1
      - window-ops==0.0.15
      - xxhash==3.5.0
      - yarl==1.2.0
