target:
- stock_exret
continuous_cols:
- ret_eom
- SHRCD
- EXCHCD
- mspread
- RF
- eps_medest
- eps_meanest
- eps_stdevest
- eps_actual
- prc
- market_equity
- div12m_me
- chcsho_12m
- eqnpo_12m
- ret_1_0
- ret_3_1
- ret_6_1
- ret_9_1
- ret_12_1
- ret_12_7
- ret_60_12
- seas_1_1an
- seas_1_1na
- seas_2_5an
- seas_2_5na
- at_gr1
- sale_gr1
- capx_gr1
- inv_gr1
- debt_gr3
- sale_gr3
- capx_gr3
- inv_gr1a
- lti_gr1a
- sti_gr1a
- coa_gr1a
- col_gr1a
- cowc_gr1a
- ncoa_gr1a
- ncol_gr1a
- nncoa_gr1a
- fnl_gr1a
- nfna_gr1a
- tax_gr1a
- be_gr1a
- ebit_sale
- gp_at
- cop_at
- ope_be
- ni_be
- ebit_bev
- netis_at
- eqnetis_at
- dbnetis_at
- oaccruals_at
- oaccruals_ni
- taccruals_at
- taccruals_ni
- noa_at
- opex_at
- at_turnover
- sale_bev
- rd_sale
- cash_at
- sale_emp_gr1
- emp_gr1
- ni_inc8q
- noa_gr1a
- ppeinv_gr1a
- lnoa_gr1a
- capx_gr2
- saleq_gr1
- niq_be
- niq_at
- niq_be_chg1
- niq_at_chg1
- rd5_at
- dsale_dinv
- dsale_drec
- dgp_dsale
- dsale_dsga
- saleq_su
- niq_su
- capex_abn
- op_atl1
- gp_atl1
- ope_bel1
- cop_atl1
- pi_nix
- ocf_at
- op_at
- ocf_at_chg1
- at_be
- ocfq_saleq_std
- tangibility
- earnings_variability
- aliq_at
- f_score
- o_score
- z_score
- intrinsic_value
- kz_index
- ni_ar1
- ni_ivol
- at_me
- be_me
- debt_me
- netdebt_me
- sale_me
- ni_me
- ocf_me
- fcf_me
- eqpo_me
- eqnpo_me
- rd_me
- bev_mev
- ebitda_mev
- aliq_mat
- eq_dur
- beta_60m
- resff3_12_1
- resff3_6_1
- mispricing_mgmt
- mispricing_perf
- ivol_capm_21d
- iskew_capm_21d
- coskew_21d
- beta_dimson_21d
- ivol_ff3_21d
- iskew_ff3_21d
- ivol_hxz4_21d
- iskew_hxz4_21d
- rmax5_21d
- rmax1_21d
- rvol_21d
- rskew_21d
- zero_trades_21d
- dolvol_126d
- dolvol_var_126d
- turnover_126d
- turnover_var_126d
- zero_trades_126d
- zero_trades_252d
- ami_126d
- ivol_capm_252d
- prc_highprc_252d
- betadown_252d
- bidaskhl_21d
- corr_1260d
- betabab_1260d
- rmax5_rvol_21d
- age
- qmj
- qmj_prof
- qmj_growth
- qmj_safety
- earnings_surprise
- accruals
- asset_growth
- momentum_1m
- momentum_3m
- momentum_6m
- momentum_12m
- quality_roe
- quality_cfo_assets
- month_2
- month_3
- month_4
- month_5
- month_6
- month_7
- month_8
- month_9
- month_10
- month_11
- month_12
categorical_cols:
- size_port
- stock_ticker
- CUSIP
- comp_name
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
dataloader_kwargs: {}
task: regression
head: LinearHead
head_config:
  layers: 128-64
  activation: ReLU
  dropout: 0.1
  use_batch_norm: false
embedding_dims:
- - 3
  - 2
- - 8191
  - 50
- - 8748
  - 50
- - 8759
  - 50
embedding_dropout: 0.1
batch_norm_continuous_input: true
learning_rate: 0.0001
loss: MSELoss
metrics:
- mean_squared_error
metrics_prob_input:
- false
metrics_params:
- {}
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.ft_transformer
_model_name: FTTransformerModel
_backbone_name: FTTransformerBackbone
_config_name: FTTransformerConfig
input_embed_dim: 32
embedding_initialization: kaiming_uniform
embedding_bias: true
share_embedding: false
share_embedding_strategy: fraction
shared_embedding_fraction: 0.25
attn_feature_importance: true
num_heads: 4
num_attn_blocks: 3
transformer_head_dim: null
attn_dropout: 0.1
add_norm_dropout: 0.1
ff_dropout: 0.1
ff_hidden_multiplier: 4
transformer_activation: GEGLU
batch_size: 1024
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 5
min_epochs: 1
max_time: null
accelerator: cpu
devices: 1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 3
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: rich
precision: 32
trainer_kwargs: {}
project_name: fine695_fttransformer
run_name: FTTransformer
exp_watch: gradients
log_target: tensorboard
log_logits: false
exp_log_freq: 100
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 4
continuous_dim: 176
output_dim: 1
output_cardinality: null
categorical_cardinality:
- 3
- 8191
- 8748
- 8759
embedded_cat_dim: 152
